export const videos = [
  {
    video_id: "3mbWMXQ-j6A",
    title:
      "From the Bottom of My Happy Heart | Ep 9 | Bad Friends with Andrew Santino & Bobby Lee",
    author: "Bad Friends",
    number_of_views: 1034453,
    video_length: "1:18:54",
    description: null,
    is_live_content: null,
    published_time: "4 years ago",
    channel_id: "UCRBpynZV0b7ww2XMCfC17qg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/3mbWMXQ-j6A/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBvB8knBQQlMML06qZtEmMZsYFSPw",
        width: 168,
        height: 94,
      },
      {
        url: "https://i.ytimg.com/vi/3mbWMXQ-j6A/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCXuMc8xHmxOZcmm-iITurySe1T8A",
        width: 336,
        height: 188,
      },
    ],
  },
  {
    video_id: "iS1GvuhmSMk",
    title:
      "Bad Friends Worldwide | Ep 12 | Bad Friends with Andrew Santino and Bobby Lee",
    author: "Bad Friends",
    number_of_views: 1847530,
    video_length: "1:39:44",
    description: null,
    is_live_content: null,
    published_time: "4 years ago",
    channel_id: "UCRBpynZV0b7ww2XMCfC17qg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/iS1GvuhmSMk/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBGPLXOY9g4GnLlB9v7eT7vBcOwMA",
        width: 168,
        height: 94,
      },
      {
        url: "https://i.ytimg.com/vi/iS1GvuhmSMk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAYghnZ_E75xCbT6v7QMXTaJMm-wg",
        width: 336,
        height: 188,
      },
    ],
  },
  {
    video_id: "H0PZ_vBZcVo",
    title:
      "Three Hundred Hussies  | Ep 10 | Bad Friends with Andrew Santino and Bobby Lee",
    author: "Bad Friends",
    number_of_views: 2466270,
    video_length: "1:31:51",
    description: null,
    is_live_content: null,
    published_time: "4 years ago",
    channel_id: "UCRBpynZV0b7ww2XMCfC17qg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/H0PZ_vBZcVo/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDVejDlcE6DH3Mpd_YoiaC4oIX_oA",
        width: 168,
        height: 94,
      },
      {
        url: "https://i.ytimg.com/vi/H0PZ_vBZcVo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDZ0zjFFhrLXfs6YlkJMF9bNYLl4g",
        width: 336,
        height: 188,
      },
    ],
  },
  {
    video_id: "V8tqHHnlLRw",
    title:
      "Bobby Floods the House and Rudy Gets Payback | Ep 26 | Bad Friends",
    author: "Bad Friends",
    number_of_views: 1579374,
    video_length: "1:10:51",
    description: null,
    is_live_content: null,
    published_time: "4 years ago",
    channel_id: "UCRBpynZV0b7ww2XMCfC17qg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/V8tqHHnlLRw/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDxCK2J13af27Ou48EKQi2DJ83bJg",
        width: 168,
        height: 94,
      },
      {
        url: "https://i.ytimg.com/vi/V8tqHHnlLRw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBAg3FaTY_BUc1BpcrN0URKRQcDag",
        width: 336,
        height: 188,
      },
    ],
  },
  {
    video_id: "lF281tABrHM",
    title:
      "Rudy's Getting Kicked Out | Ep 15 | Bad Friends with Andrew Santino and Bobby Lee",
    author: "Bad Friends",
    number_of_views: 1846618,
    video_length: "1:22:10",
    description: null,
    is_live_content: null,
    published_time: "4 years ago",
    channel_id: "UCRBpynZV0b7ww2XMCfC17qg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/lF281tABrHM/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLD-c1V3BMKtoA2SGNj1nTG1eK02vw",
        width: 168,
        height: 94,
      },
      {
        url: "https://i.ytimg.com/vi/lF281tABrHM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB5AKToEuz4l4PXLAi_gOh4eidO2g",
        width: 336,
        height: 188,
      },
    ],
  },
  {
    video_id: "730p91Qiuig",
    title:
      "Bobo’s Magic Calf Cream | Ep 20 | Bad Friends with Andrew Santino and Bobby Lee",
    author: "Bad Friends",
    number_of_views: 1320101,
    video_length: "1:09:24",
    description: null,
    is_live_content: null,
    published_time: "4 years ago",
    channel_id: "UCRBpynZV0b7ww2XMCfC17qg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/730p91Qiuig/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCZSfQkt6oNYnJbnOr_EpclwPiV-Q",
        width: 168,
        height: 94,
      },
      {
        url: "https://i.ytimg.com/vi/730p91Qiuig/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCj310hGqqRKPbMltCaV_2_Bc2CYw",
        width: 336,
        height: 188,
      },
    ],
  },
  {
    video_id: "WWXug3ZBa5U",
    title:
      "The Yin and Yang of Earthquakes | Ep 25 | Bad Friends with Andrew Santino and Bobby Lee",
    author: "Bad Friends",
    number_of_views: 1836562,
    video_length: "1:19:41",
    description: null,
    is_live_content: null,
    published_time: "4 years ago",
    channel_id: "UCRBpynZV0b7ww2XMCfC17qg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/WWXug3ZBa5U/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDtgqznmQiyeJhEq3G7yz_UHqvupg",
        width: 168,
        height: 94,
      },
      {
        url: "https://i.ytimg.com/vi/WWXug3ZBa5U/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAJcoeTEL_hHCfGYk9EC1IzBoEsWQ",
        width: 336,
        height: 188,
      },
    ],
  },
  {
    video_id: "B848cb6gRg4",
    title:
      "Hi, America! | Ep 6 | Bad Friends with Andrew Santino and Bobby Lee",
    author: "Bad Friends",
    number_of_views: 2870979,
    video_length: "1:42:09",
    description: null,
    is_live_content: null,
    published_time: "5 years ago",
    channel_id: "UCRBpynZV0b7ww2XMCfC17qg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/B848cb6gRg4/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDwz7jEXVeXzVMgJ0IdG3RiYY3QLQ",
        width: 168,
        height: 94,
      },
      {
        url: "https://i.ytimg.com/vi/B848cb6gRg4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDLZI7A6yINlsF9jNJEJMTklHevoA",
        width: 336,
        height: 188,
      },
    ],
  },
  {
    video_id: "aeqSrVrhi_8",
    title:
      "Great Start, Fantastic Finish! | Ep 2 | Bad Friends with Andrew Santino & Bobby Lee",
    author: "Bad Friends",
    number_of_views: 1869449,
    video_length: "1:32:57",
    description: null,
    is_live_content: null,
    published_time: "5 years ago",
    channel_id: "UCRBpynZV0b7ww2XMCfC17qg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/aeqSrVrhi_8/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAsiJySDBEJpTxU-clvn3176hgOjQ",
        width: 168,
        height: 94,
      },
      {
        url: "https://i.ytimg.com/vi/aeqSrVrhi_8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCPR90slsvyKkg1vXjrio1wOU4NTQ",
        width: 336,
        height: 188,
      },
    ],
  },
  {
    video_id: "ycje82IVIJM",
    title:
      "Andrew Santino, You Hit the Nail with the Nail | Bonus TigerBelly",
    author: "TigerBelly",
    number_of_views: 1121988,
    video_length: "1:13:38",
    description: null,
    is_live_content: null,
    published_time: "5 years ago",
    channel_id: "UCIyIoM_Nd8HtY19fuR_ov2A",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/ycje82IVIJM/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBIxzD4h4PkCa3qmmMGbIszilkJNQ",
        width: 168,
        height: 94,
      },
      {
        url: "https://i.ytimg.com/vi/ycje82IVIJM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAngnzDiLcUhvbgowBJZnwmd_zhJg",
        width: 336,
        height: 188,
      },
    ],
  },
  {
    video_id: "DIf3sDbsurs",
    title: "Santino Hits Bobby and Rudy’s Birthday! | Ep 39 | Bad Friends",
    author: "Bad Friends",
    number_of_views: 1482003,
    video_length: "1:24:48",
    description: null,
    is_live_content: null,
    published_time: "4 years ago",
    channel_id: "UCRBpynZV0b7ww2XMCfC17qg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/DIf3sDbsurs/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLA4XC2cei0qnOFS_tHSVvT1R12iow",
        width: 168,
        height: 94,
      },
      {
        url: "https://i.ytimg.com/vi/DIf3sDbsurs/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAdASyEg63xgFmSup-imU-_ykQvcQ",
        width: 336,
        height: 188,
      },
    ],
  },
  {
    video_id: "XugYikh6yjQ",
    title:
      "Shoot The TV | Ep 3 | Bad Friends with Andrew Santino & Bobby Lee",
    author: "Bad Friends",
    number_of_views: 1631078,
    video_length: "1:23:57",
    description: null,
    is_live_content: null,
    published_time: "5 years ago",
    channel_id: "UCRBpynZV0b7ww2XMCfC17qg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/XugYikh6yjQ/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDAVXCHBK5bFWyTZBxZhHvrQKJOYQ",
        width: 168,
        height: 94,
      },
      {
        url: "https://i.ytimg.com/vi/XugYikh6yjQ/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLATGBE1KsbYZNw57uOGJQmauV05tw",
        width: 336,
        height: 188,
      },
    ],
  },
  {
    video_id: "ZE5kacxG75o",
    title:
      "Bobby Lee Offended by Andrew Santino’s Art Tastes | Bad Friends Clips",
    author: "Bad Friends Clips",
    number_of_views: 782198,
    video_length: "14:37",
    description: null,
    is_live_content: null,
    published_time: "4 years ago",
    channel_id: "UCmuRHGhh-g0f9f5JiuW6dMw",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/ZE5kacxG75o/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCpat1aE15vIhjVYfGu2h_XMKszew",
        width: 168,
        height: 94,
      },
      {
        url: "https://i.ytimg.com/vi/ZE5kacxG75o/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA3AXtGd8b_Q5lO_o9LvtumknfMxw",
        width: 336,
        height: 188,
      },
    ],
  },
  {
    video_id: "30TWdWxsJpU",
    title: "Rudy Runs for VP & The Podcast Guys Tour! | Ep 27 | Bad Friends",
    author: "Bad Friends",
    number_of_views: 2197334,
    video_length: "1:31:23",
    description: null,
    is_live_content: null,
    published_time: "4 years ago",
    channel_id: "UCRBpynZV0b7ww2XMCfC17qg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/30TWdWxsJpU/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDR_qn3ikIQWKKTtJI6L7aNIcddRA",
        width: 168,
        height: 94,
      },
      {
        url: "https://i.ytimg.com/vi/30TWdWxsJpU/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCbJsH7EQ26adwhSczyA0S7JRa3Ng",
        width: 336,
        height: 188,
      },
    ],
  },
  {
    video_id: "gROAUOn-W88",
    title:
      "Daddy Why You Die? | Ep 19 | Bad Friends with Andrew Santino and Bobby Lee",
    author: "Bad Friends",
    number_of_views: 1805804,
    video_length: "1:25:16",
    description: null,
    is_live_content: null,
    published_time: "4 years ago",
    channel_id: "UCRBpynZV0b7ww2XMCfC17qg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/gROAUOn-W88/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCAQltKEATuVB-0GRtVxYEyuG6eTg",
        width: 168,
        height: 94,
      },
      {
        url: "https://i.ytimg.com/vi/gROAUOn-W88/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDBA5n_-XG73IhYiazVcm_vf1_lFQ",
        width: 336,
        height: 188,
      },
    ],
  },
  {
    video_id: "MoelHCIMny8",
    title: "Jiaoying Summers Banned from TikTok | TigerBelly 396",
    author: "TigerBelly",
    number_of_views: 372230,
    video_length: "1:10:36",
    description: null,
    is_live_content: null,
    published_time: "1 year ago",
    channel_id: "UCIyIoM_Nd8HtY19fuR_ov2A",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/MoelHCIMny8/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAlvEgoFanVtOHbZPXa0KtStDqFwg",
        width: 168,
        height: 94,
      },
      {
        url: "https://i.ytimg.com/vi/MoelHCIMny8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBSmH4krf7UIWY3fbz16kIWlq_48A",
        width: 336,
        height: 188,
      },
    ],
  },
  {
    video_id: "aFuvgbYeRAw",
    title: "Theo Von, Beat 'Em and Eat 'Em! | TigerBelly 319",
    author: "TigerBelly",
    number_of_views: 2525091,
    video_length: "1:16:27",
    description: null,
    is_live_content: null,
    published_time: "3 years ago",
    channel_id: "UCIyIoM_Nd8HtY19fuR_ov2A",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/aFuvgbYeRAw/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDdDFZNHNTdPV7_C1DRpWHKmkkztA",
        width: 168,
        height: 94,
      },
      {
        url: "https://i.ytimg.com/vi/aFuvgbYeRAw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDWhaOoOrTEKg36TcnWr15-1pNGvQ",
        width: 336,
        height: 188,
      },
    ],
  },
  {
    video_id: "krcsGDTFM3Y",
    title: "Bobby Lee Exposing Rudy For 30 Minutes Straight (Bad Friends)",
    author: "Tito Turtle",
    number_of_views: 1306859,
    video_length: "31:31",
    description: null,
    is_live_content: null,
    published_time: "2 years ago",
    channel_id: "UCw8FYPxUh6RAgBLq6kTEtAg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/krcsGDTFM3Y/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBXmKTb7gL_DM8zZ7YmndDqjnarmg",
        width: 168,
        height: 94,
      },
      {
        url: "https://i.ytimg.com/vi/krcsGDTFM3Y/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDo4-VBHpZL0pZWa-aC1ck4QYmhDw",
        width: 336,
        height: 188,
      },
    ],
  },
  {
    video_id: "IOQCYpljQdQ",
    title: "Bobo's Big Head and Rudy Wins an Oscar! | Ep 30 | Bad Friends",
    author: "Bad Friends",
    number_of_views: 1853479,
    video_length: "1:33:56",
    description: null,
    is_live_content: null,
    published_time: "4 years ago",
    channel_id: "UCRBpynZV0b7ww2XMCfC17qg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/IOQCYpljQdQ/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLB1YWZLHKtP8xzMnpJjLjLfWtvwDA",
        width: 168,
        height: 94,
      },
      {
        url: "https://i.ytimg.com/vi/IOQCYpljQdQ/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD8GwWAKU8VQt8VuEfXpP_cM8rAJw",
        width: 336,
        height: 188,
      },
    ],
  },
  {
    video_id: "05mNivLBMkw",
    title: "Ep. 74 | 2 Bears, 1 Cave w/ Andrew Santino & Bobby Lee",
    author: "YMH Studios",
    number_of_views: 3086767,
    video_length: "1:37:43",
    description: null,
    is_live_content: null,
    published_time: "3 years ago",
    channel_id: "UCYIgiXwJck_Pb5Nj-wIrsqg",
    category: null,
    type: "NORMAL",
    keywords: [],
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/05mNivLBMkw/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCGi0nw0hxRR0IicX2A4Mltjz-35Q",
        width: 168,
        height: 94,
      },
      {
        url: "https://i.ytimg.com/vi/05mNivLBMkw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCnOwWaGCil50ZuHDbI9ijfXmVqwA",
        width: 336,
        height: 188,
      },
    ],
  },
] 